### ISSUE TITLE
Faroese tagset

### ISSUE THREAD

**Issue by dan-zeman** [dan-zeman/interset#3]
In https://github.com/UniversalDependencies/docs/issues/336, @Bjartensen posted a brief description of a tagset for Faroese. I have written a driver based on that description, but there are some pieces missing. For instance, the tagset does not seem to be strictly positional (not even within individual parts of speech). The description looks like nouns have always 6 characters but they don't. The affixed definite article (character 5) is optional, and `SFSNP` is a valid tag.

I would need a list of all possible tags to fix this. And ideally also a sample of tagged data, or examples of words having particular tags.

**Comment by Bjartensen** [comment]
[You can find the corpus on this site](http://stava.fo/), on the bottom ("Tak niður" is download).
[Direct link](http://stava.fo/download/tagged_corpus.zip).

Do you want just all possible tags? Or the tags and a word as an example?

**Comment by Bjartensen** [comment]
**This is pretty simple, but I think these are all the tags. The first word it occurred with is added as well.**

<pre>
SFSD    tíð
ASWMSD  seinasta
SXSG    Atlants
CI  at
VEPP2   nýtist
VI  syngja
VAMSN   hugtikin
SNPGA   landanna
PDFPA   hesar
SMPD    leirlutum
PMSD    hvørjum
SMSGA   Javnaðarfloksins
VANPA   undanfarin
PNSN    Tað
APSNPD  meistaraliðnum
SMSN    tráður
ACWFSN  seinna
ASWMPA  Seinastu
PIFSD   eini
PMPD    sínum
PIFSA   eina
NCMSA   20
ACWFSD  seinnu
P1PA    míni
PIFPN   báðar
ACSNSD  eldri
ASSFSN  besta
VEPS2   kanst
VNPS2   arbeiðir
SFSNA   treytin
I   Jú
ACSMSN  skjótari
PDMSA   Hendan
VNAS2   vart
PIMSN   ein
EN  fyri
VEAS3   sjólótust
VAFPA   útsettar
APWFSA  vanvarda
NONSN   fyrsta
ACSFPN  fleiri
APWFSN  Árliga
PINPA   nøkur
ASSFPD  innastu
NONSA   fyrsta
VNPP1   hoyra
PFSA    Hvørja
ASWFSA  seinastu
VANSD   bygdum
PDNSA   hetta
P2SG    tín
PIMSA   ein
»  »
SMSNAP  Ejvin
SNSNL   Svøríki
NCNSA   eitt
PDFPN   hinar
PDMPA   hinar
P2PG    Tygara
SFPAL   Føroyar
VE  noyddust
ASSFSD  nærmastu
SMSNP   Jan
?   ?
SMPDL   Heygum
VAFPN   blástar
VAFSA   tillutaða
ACWNSN  róligari
NCFSA   eina
APSNSA  skinklut
ACWNPN  smærru
VAMPA   sett
NONSD   øðrum
SNSAAL  Sundið
NOMSG   8.
SMSAL   Sørvágsfjørð
SFPG    handa
ACSNSN  lættari
APSMSD  heilum
ACWMPD  nýggjaru
X   umum
SMPNA   møguleikarnir
ACSMSD  seinna
%   %
PFPG    teirra
SMSAA   lutin
C   at
NONPD   fýra
SNPG    ára
SNPDL   Argjum
SNPNL   Norðurlond
PIMPN   nakrir
SFSGL   Tórshavnar
PINPN   onnur
ACSFSN  Størri
VNPS1   vil
PFPN    Tær
PIFPA   onkrar
PDNPD   teimum
ACSNSA  størri
ASSNSA  fínasta
ASWMPN  hóvligaru
DA  øðrvísi
NMSA    tveir
NCNSN   eitt
APWNPA  ymsu
NOMSD   sekunda
PNSA    tað
SNSA    verk
APWMPN  Føroysku
NOMSN   1
SNSD    leiri
ED  í
-   -
SFSN    skipan
SNSNP   Fróðskaparsetur
«  «
SFPDA   veljarakanningunum
ACWFSA  betri
ASWNSN  fyrsta
SMSGP   Svensson
ASWFPD  fyrstu
SFPDL   Føroyum
SFSAA   treytina
APSFPA  stórar
´  ´
SNSAL   Kollaskarð
APWNSD  danska
PFSD    sær
F   FC
VAFPD   samlaðu
VANSA   vanvarda
DSA flest
DG  slettis
ACSFPD  fleiri
PMSA    hvønn
NOFSN   fyrstu
DCA longri
ASSNSN  besta
SNPA    ár
ASSNPD  flestu
SMPG    fedranna
VNAS3   lat
)   )
SFSNP   Guðrið
SFPD    verum
NCNPD   tveimum
SFPNL   Føroyar
VNAP3   kundu
SX  senn
APSMSA  serligan
VAFSN   Gjørd
PFSG    sína
SMSG    fyrimuns
APWFSD  árligu
APSFPD  smáum
ASWNPD  flestu
DCD minni
EG  til
SNSNAP  Norðurlandaráðið
:   :
APWNPD  einstøku
SNPDA   listaverkunum
NC  10.000
ACWMSA  fínara
ACSMSA  betri
N0FSA   triðju
ACSFSD  norðaru
APWFPA  allar
NMPA    tveir
APWNSA  stóra
ACWFPN  smærru
ACSFSA  fyrru
PINSN   Eitt
VEPP1   noyðast
PINPD   øðrum
NO  2
P1SN    Eg
PDFSD   teirri
APWMSA  svenska
VEPS1   ivist
NCMPN   tveir
APSNSD  nýggja
P1SA    meg
PNSD    tí
SMSA    boðskap
NCMPD   trimum
SFPN    myndir
ACSNPN  Fleiri
APSFPN  nógvar
NCNPA   tvey
SNSG    dømis
SNSDAL  Eiðinum
PDFSA   hesa
ACSFPA  fleiri
ASWFPA  Seinastu
NCMPA   tveir
ASWMSA  størsta
SMPAA   tríburarnar
PIFPD   ongum
NOFSA   fyrstu
ASSMPA  seinastu
APWFPG  humdraðtals
ASWNSA  einasta
APWMSN  gamli
PINSA   eitt
NOMPD   tíggju
ACWMSN  lægri
PFSN    hon
&   &
PMPN    teir
PINSD   einum
ACWMPN  eldru
VMS Lat
P1PN    vit
ACSNPA  fleiri
P1PG    okkara
APSMPA  somu
P1PD    okkum
PIFSN   ein
VAMSA   settan
P1SD    mær
SFSDP   Guðrið
P2SN    tú
PNPG    teirra
PMPG    teirra
SFPAA   Myndirnar
PMPA    seg
VAFSD   kravdari
SNPAA   verkini
APWMPD  donsku
ASSNPN  flestu
ASSMPN  Flestu
VANPN   Vanvard
SFSAP   Maritu
APSNSN  Vanvart
VAMPD   umrøddu
PDMSN   tann
PIMPA   aðrar
ASSFPN  Flestu
APWMPA  lágu
T   HB
PIMPD   hvønnannan
SMSDL   Fuglafirðið
PMSG    hansara
VNPS3   støkkur
!   !
APSMPN  Vónbrotnir
SFSDL   Keypmannahavn
SFSA    Varmakeldu
PNPA    tey
SFPA    fillur
NONPA   Annað
SFPNA   Fráboðanirnar
/   /
PMSN    hann
ACWFPD  ytri
SXL Lund
SNPN    skapanarverk
PFPA    seg
'   '
.   .
PNPN    øll
SNSNA   ljósið
APSNPN  sjálvi
AI  týðandi
VMP Sláið
APSMSN  reyður
VEAP1   stríddust
VEPS3   sæst
PDNSN   Hetta
SMSNL   Eiriksboði
VNPP3   hava
NCMSN   ein
SMPN    lutir
SMPGA   flokkanna
ASWFSN  elsta
ASSMSA  næstseinasta
PDNPA   hesi
ACWFPA  størru
SFSNL   Klaksvík
SFSG    hvíldar
SMSDAP  Teistanum
SFSAAL  Suðuroynna
APSNPA  skilagóð
­  ­
SFSGP   Mariu
SNSDP   Fróðskaparsetri
VNAP1   spurdu
P1SG    mítt
SNPD    skapum
DSN mest
APSFSA  nýggja
P2SD    tær
P2SA    teg
VA  gjørt
SNSGL   Íslands
VAMPN   bodnir
ASWMSN  Fyrsti
SFSAL   Havn
;   ;
NCNSD   einum
ASSMSN  størsti
SMSDP   Jens
DCN víðari
VNPP2   mugu
PDNSD   hesum
NOMSA   21
ACSMPN  fleiri
ASWNSD  nýggjasta
PNSG    tess
SFSDAL  Havnini
APWNSN  gamla
ASSNSD  ringasta
PDMSD   hinum
PDMPN   teir
CR  sum
PDFPD   teimum
NCFPN   Tvær
APWFPN  allar
VP  kitlandi
PDFSN   Hendan
ACWNPD  fleiri
APSMPD  smáum
SFSDA   ferniseringini
SNPNA   listaverkini
ASWFPN  flestu
PDMPD   hesum
PDNPN   Tey
ACWNPA  seinnu
SMSGL   Vágs
NOFSD   fyrstu
NCFPA   14
ASSFSA  seinasta
SFPGL   Norðoya
SNSAA   hølið
DD  frammanfyri
NCMPG   átta
DN  sjálvt
SMPDA   lutunum
SNSDA   samanspælinum
ASSMSD  størsta
SMSDAL  Sundsvegnum
PNPD    teimum
APWFSG  Heilsufrøðiligu
ASWNPN  flestu
SMSDA   huganum
NOFSG   1
SMPA    møguleikar
"   "
(   (
SXP Poulsen
NCFPD   tveimum
,   ,
VEAP3   hittust
ACSNPD  lægri
SMSAP   Jógvan
SMSNA   Vandin
VAMSD   øktum
VANSN   samlað
PFPD    teimum
SFSNAL  Vágoyggin
SFPDAL  Vágunum
P2PN    tit
SNSDL   Riberhúsi
SFNSDL  Tvøroyri
SXSD    gjár
AO  týðandi
NCNPN   tvey
VEAS2   noyddist
APSFSN  vistfrøðiliga
ACSMPA  fleiri
SNSN    dýpi
VEPP3   tykist
PIMSD   einum
APWMSD  sjálvum
ASWFSD  seinastu
APWNPN  almennu
VANPD   innsiglaðum
SNSGA   felagsins
APWFPD  vanligu
EA  til
ACWNSA  seinna
APSFSD  dýrari
ASSNPA  seinastu
SNSNAL  Sundið
VNAS1   valdi
SMSD    málningi
ASWNPA  seinastu
NCFSN   ein
ACSMPD  fleiri
SFSGA   nevndarinnar
</pre>

**Comment by dan-zeman** [comment]
Great, thanks! I actually took the corpus. It also helped to identify a few typos in the tags.
